[DO NOT MERGE] Updates token to bit/s where necessary.
entropyxyz/entropy-docs pull request #266
Opened 2024-11-18 14:43 UTC by johnnymatthews

Closes https://github.com/entropyxyz/entropy-docs/issues/265

2024-12-03 15:03 UTC, johnnymatthews commented
Tagged @frankiebee @mixmix and @rh0delta for a review. Only really need a single review from someone though; all three is overkill for such a small PR.

2024-12-03 20:26 UTC, mixmix requested changes
**Requested change**
- [ ] consistent capitalisation
  -  `BITS` not `bits`
  - `nanoBITS` not `nanobits`

**Recommended to consider**
- [ ] do we singularise or are we always plural units?  i.e. is  `BIT` a thing?
- [ ] we may be changing from `nanoBITS` to `lilBITS`
  - hmm `lilBITS` is pretty hard to read. maybe we defer that

2024-12-03 20:26 UTC, mixmix commented on content/basics/glossary.md
> +The token uses to perform transactions on the Entropy blockchain. 1 `bit` is equal to 10,000,000,000 `nanoBITS`.
I think the unit should be consistently capitalised, and maybe even pluralised? i.e. `BIT` or `BITS`

2024-12-04 13:51 UTC, johnnymatthews commented on content/basics/glossary.md
> +The token uses to perform transactions on the Entropy blockchain. 1 `bit` is equal to 10,000,000,000 `nanoBITS`.
Good shout. I'll sort that out now.

2025-02-18 14:51 UTC, closed without merging